services:
  db:
    image: postgres:16-alpine
    container_name: linkvault_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:5432"
    volumes:
      - linkvault_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - linkvault_network

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: linkvault_api
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8080:8080"

    depends_on:
      db:
        condition: service_healthy

    networks:
      - linkvault_network


volumes:
  linkvault_pgdata:

networks:
  linkvault_network:
    driver: bridge