// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: bookmarks.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createBookmark = `-- name: CreateBookmark :one
INSERT INTO
    bookmarks (
        user_id,
        url,
        title,
        description,
        favicon_url,
        metadata_fetched
    )
VALUES
    ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, url, title, description, favicon_url, is_public, metadata_fetched, created_at, updated_at
`

type CreateBookmarkParams struct {
	UserID          uuid.UUID      `json:"user_id"`
	Url             interface{}    `json:"url"`
	Title           sql.NullString `json:"title"`
	Description     sql.NullString `json:"description"`
	FaviconUrl      sql.NullString `json:"favicon_url"`
	MetadataFetched bool           `json:"metadata_fetched"`
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, createBookmark,
		arg.UserID,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.FaviconUrl,
		arg.MetadataFetched,
	)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.FaviconUrl,
		&i.IsPublic,
		&i.MetadataFetched,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM bookmarks WHERE id = $1 AND user_id = $2
`

type DeleteBookmarkParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, deleteBookmark, arg.ID, arg.UserID)
	return err
}

const getBookmarkByID = `-- name: GetBookmarkByID :one
SELECT id, user_id, url, title, description, favicon_url, is_public, metadata_fetched, created_at, updated_at FROM bookmarks
WHERE id = $1 AND user_id = $2
ORDER BY created_at DESC
`

type GetBookmarkByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetBookmarkByID(ctx context.Context, arg GetBookmarkByIDParams) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, getBookmarkByID, arg.ID, arg.UserID)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.FaviconUrl,
		&i.IsPublic,
		&i.MetadataFetched,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookmarksByUser = `-- name: ListBookmarksByUser :many
SELECT id, user_id, url, title, description, favicon_url, is_public, metadata_fetched, created_at, updated_at FROM bookmarks WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBookmarksByUser(ctx context.Context, userID uuid.UUID) ([]Bookmark, error) {
	rows, err := q.db.QueryContext(ctx, listBookmarksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bookmark{}
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.FaviconUrl,
			&i.IsPublic,
			&i.MetadataFetched,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnfetchedBookmarks = `-- name: ListUnfetchedBookmarks :many
SELECT id, user_id, url, title, description, favicon_url, is_public, metadata_fetched, created_at, updated_at FROM bookmarks WHERE metadata_fetched = false LIMIT 50
`

func (q *Queries) ListUnfetchedBookmarks(ctx context.Context) ([]Bookmark, error) {
	rows, err := q.db.QueryContext(ctx, listUnfetchedBookmarks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bookmark{}
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.FaviconUrl,
			&i.IsPublic,
			&i.MetadataFetched,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookmark = `-- name: UpdateBookmark :one
UPDATE bookmarks SET
    url = $1,
    title = $2,
    description = $3,
    is_public = $4,
    updated_at = NOW()
WHERE id = $5 AND user_id = $6
RETURNING id, user_id, url, title, description, favicon_url, is_public, metadata_fetched, created_at, updated_at
`

type UpdateBookmarkParams struct {
	Url         interface{}    `json:"url"`
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
	IsPublic    bool           `json:"is_public"`
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateBookmark(ctx context.Context, arg UpdateBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, updateBookmark,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.IsPublic,
		arg.ID,
		arg.UserID,
	)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.FaviconUrl,
		&i.IsPublic,
		&i.MetadataFetched,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBookmarkMetadata = `-- name: UpdateBookmarkMetadata :one
UPDATE bookmarks SET
    title= $1,
    description = $2,
    favicon_url = $3,
    metadata_fetched = true,
    updated_at = NOW()
WHERE id = $4 AND user_id = $5
RETURNING id, user_id, url, title, description, favicon_url, is_public, metadata_fetched, created_at, updated_at
`

type UpdateBookmarkMetadataParams struct {
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
	FaviconUrl  sql.NullString `json:"favicon_url"`
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateBookmarkMetadata(ctx context.Context, arg UpdateBookmarkMetadataParams) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, updateBookmarkMetadata,
		arg.Title,
		arg.Description,
		arg.FaviconUrl,
		arg.ID,
		arg.UserID,
	)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.FaviconUrl,
		&i.IsPublic,
		&i.MetadataFetched,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
