// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Bookmark struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	Url             interface{}    `json:"url"`
	Title           sql.NullString `json:"title"`
	Description     sql.NullString `json:"description"`
	FaviconUrl      sql.NullString `json:"favicon_url"`
	IsPublic        bool           `json:"is_public"`
	MetadataFetched bool           `json:"metadata_fetched"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type BookmarkTag struct {
	BookmarkID uuid.UUID `json:"bookmark_id"`
	TagID      uuid.UUID `json:"tag_id"`
}

type Tag struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
