// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddTagToBookmark(ctx context.Context, arg AddTagToBookmarkParams) error
	CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (Bookmark, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error
	DeleteTag(ctx context.Context, arg DeleteTagParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetBookmarkByID(ctx context.Context, arg GetBookmarkByIDParams) (Bookmark, error)
	GetTagByID(ctx context.Context, arg GetTagByIDParams) (Tag, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListBookmarksByUser(ctx context.Context, userID uuid.UUID) ([]Bookmark, error)
	ListTagsByBookmark(ctx context.Context, bookmarkID uuid.UUID) ([]Tag, error)
	ListTagsByUser(ctx context.Context, userID uuid.UUID) ([]Tag, error)
	ListUnfetchedBookmarks(ctx context.Context) ([]Bookmark, error)
	RemoveBookmarkTag(ctx context.Context, arg RemoveBookmarkTagParams) error
	UpdateBookmark(ctx context.Context, arg UpdateBookmarkParams) (Bookmark, error)
	UpdateBookmarkMetadata(ctx context.Context, arg UpdateBookmarkMetadataParams) (Bookmark, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
