// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTagToBookmark = `-- name: AddTagToBookmark :exec
INSERT INTO bookmark_tags (bookmark_id, tag_id)
VALUES ($1, $2)
`

type AddTagToBookmarkParams struct {
	BookmarkID uuid.UUID `json:"bookmark_id"`
	TagID      uuid.UUID `json:"tag_id"`
}

func (q *Queries) AddTagToBookmark(ctx context.Context, arg AddTagToBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, addTagToBookmark, arg.BookmarkID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, created_at
`

type CreateTagParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.UserID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1 AND user_id = $2
`

type DeleteTagParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.ExecContext(ctx, deleteTag, arg.ID, arg.UserID)
	return err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, user_id, name, created_at FROM tags WHERE id = $1 AND user_id = $2
`

type GetTagByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTagByID(ctx context.Context, arg GetTagByIDParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByID, arg.ID, arg.UserID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listTagsByBookmark = `-- name: ListTagsByBookmark :many
SELECT t.id, t.user_id, t.name, t.created_at FROM tags t
JOIN bookmark_tags bt ON t.id = bt.tag_id
WHERE bt.bookmark_id = $1
`

func (q *Queries) ListTagsByBookmark(ctx context.Context, bookmarkID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByBookmark, bookmarkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByUser = `-- name: ListTagsByUser :many
SELECT id, user_id, name, created_at FROM tags WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTagsByUser(ctx context.Context, userID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBookmarkTag = `-- name: RemoveBookmarkTag :exec
DELETE FROM bookmark_tags WHERE bookmark_id = $1 AND tag_id = $2
`

type RemoveBookmarkTagParams struct {
	BookmarkID uuid.UUID `json:"bookmark_id"`
	TagID      uuid.UUID `json:"tag_id"`
}

func (q *Queries) RemoveBookmarkTag(ctx context.Context, arg RemoveBookmarkTagParams) error {
	_, err := q.db.ExecContext(ctx, removeBookmarkTag, arg.BookmarkID, arg.TagID)
	return err
}
